name: ETL CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 1 * * *"  # Optional: run every day at 01:00 UTC

jobs:
  etl-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --exclude venv --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run unit tests
        run: |
          pytest tests/  # Make sure you have a tests/ directory

        run: |
          python etl_pipeline.py
